version: '3.8'

services:
  postgres_dev:
    image: postgres:12
    container_name: postgres_hotel
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hoteldb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data: