server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/hoteldb
    username: root
    password: root
  jpa:
    show-sql: true

logging:
  level:
    com.joelmaciel.hotel_service: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka