server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb
    username: root
    password: root
  jpa:
    show-sql: true

logging:
  level:
    com.joelmaciel.hotel_service: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO